name: CI Pipeline with SAST, Dependency Scanning, and Secret Detection

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Application
        run: echo "Building the application..."

  test:
    name: Test Stage
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # SAST (Static Application Security Testing)
      - name: Run SAST
        uses: github/codeql-action/init@v2
        with:
          languages: 'javascript,python' # Adjust based on your project languages
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      # Dependency Scanning
      - name: Dependency Scanning
        uses: aquasecurity/trivy-action@v0.11.0
        with:
          scan-type: 'fs'
          severity: 'HIGH,CRITICAL'

      # Secret Detection
      - name: Secret Detection
        uses: actions/checkout@v3
      - name: Run Secret Detection
        run: |
          echo "Running secret detection..."
          # Use GitHub's built-in secret scanning or a third-party tool like truffleHog
          npx trufflehog filesystem --directory . --json

  deploy:
    name: Deploy Stage
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Application
        run: echo "Deploying the application..."
